version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:example@mongo:27017/mern_app?authSource=admin
    depends_on:
      - mongo
